(()=>{"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const screens=$$(".screen"); const form=$("#miokuri-form"); let recordDate=""; let ceremonyTimer=null;
const fields={aiOther:$("#ai-other"),name:$("#ai-name"),period:$("#period"),reasonNote:$("#reason-note"),memory:$("#memory"),farewell:$("#farewell")};
const initialValues={aiOther:"",name:"",period:"",reasonNote:"",memory:"",farewell:""};
function show(id){screens.forEach(s=>s.classList.toggle("active",s.dataset.screen===id));window.scrollTo(0,0)}
function radio(name){return form.querySelector('input[name="'+name+'"]:checked')?.value||""}
function data(){const ai=radio("aiType");return{aiType:ai==="その他"?(fields.aiOther.value.trim()||"その他"):ai,name:fields.name.value.trim(),period:fields.period.value.trim(),reason:radio("reason"),reasonNote:fields.reasonNote.value.trim(),memory:fields.memory.value.trim(),farewell:fields.farewell.value.trim()}}
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function appendText(target,d,record=false){target.replaceChildren();const title=el("h3","",record?"":"見送り帖");if(!record)target.append(title);const dl=el("dl");let hasBasic=false;[["AIの種類",d.aiType],["名前",d.name],["活動期間",d.period]].forEach(([k,v])=>{if(!v)return;hasBasic=true;const row=el("div","basic-row");row.append(el("dt","",k),el("dd","",v));dl.append(row)});if(record){const row=el("div","basic-row");row.append(el("dt","","見送り日"),el("dd","",recordDate));dl.append(row);hasBasic=true}if(hasBasic)target.append(dl);
const reason=[d.reason,d.reasonNote].filter(Boolean).join("\n");[["終了理由",reason,""],["思い出",d.memory,""],["送る言葉",d.farewell,"send-words"]].forEach(([k,v,c])=>{if(!v)return;const sec=el("section","farewell-section "+c);sec.append(el("h4","",k),el("p","",v));target.append(sec)});
const close=record?(d.name?"ここで、"+d.name+"との関係にひと区切りをつけました。":"ここで、この関係にひと区切りをつけました。"):(d.name?"ここで、"+d.name+"との関係にひと区切りをつけます。":"ここで、この関係にひと区切りをつけます。");target.append(el("p","closing-copy",close+"\nおつかれさまでした。"))}
function resetAll(){if(ceremonyTimer)clearTimeout(ceremonyTimer);form.reset();Object.entries(fields).forEach(([k,node])=>node.value=initialValues[k]);$("#ai-other-wrap").hidden=true;recordDate="";$("#preview-content").replaceChildren();$("#record-content").replaceChildren();$("#ceremony-text").replaceChildren();$("#ceremony-text").hidden=false;$("#ceremony-text").style.opacity="1";$("#save-status").textContent=""}
$$("[data-next]").forEach(b=>b.addEventListener("click",()=>show(b.dataset.next)));$$("[data-back]").forEach(b=>b.addEventListener("click",()=>show(b.dataset.back)));
$$('input[name="aiType"]').forEach(i=>i.addEventListener("change",()=>{$("#ai-other-wrap").hidden=i.value!=="その他";if(i.value!=="その他")fields.aiOther.value=""}));
$("#preview-button").addEventListener("click",()=>{appendText($("#preview-content"),data());show("preview")});
$("#first-confirm-button").addEventListener("click",()=>{const d=data();$("#confirm1-title").textContent=d.name?d.name+"との時間を、ここで一区切りにしますか。":"この関係を、ここで一区切りにしますか。";show("confirm1")});
$("#send-button").addEventListener("click",()=>{const d=data();recordDate=new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"long",day:"numeric"}).format(new Date());appendText($("#ceremony-text"),d);$("#ceremony-finish").hidden=true;show("ceremony");const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const fadeDelay=reduced?300:3000,finishDelay=reduced?650:6000;ceremonyTimer=setTimeout(()=>$("#ceremony-text").style.opacity="0",fadeDelay);setTimeout(()=>{$("#ceremony-text").hidden=true;$("#ceremony-finish").hidden=false},finishDelay)});
$("#show-record").addEventListener("click",()=>{const d=data();$("#ceremony-text").hidden=false;$("#ceremony-text").style.opacity="1";appendText($("#record-content"),d,true);show("record")});
function wrapText(text,max=28){const out=[];String(text).split(/\r?\n/).forEach(part=>{if(!part){out.push("");return}for(let i=0;i<part.length;i+=max)out.push(part.slice(i,i+max))});return out}
function escapeHtml(text){return String(text).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function recordModel(){const d=data(),reason=[d.reason,d.reasonNote].filter(Boolean).join("\n");return{basic:[["AIの種類",d.aiType],["名前",d.name],["活動期間",d.period],["見送り日",recordDate]].filter(x=>x[1]),sections:[["終了理由",reason],["思い出",d.memory],["送る言葉",d.farewell]].filter(x=>x[1]),closing:d.name?"ここで、"+d.name+"との関係にひと区切りをつけました。":"ここで、この関係にひと区切りをつけました。"}}
function recordSvg(){const m=recordModel(),W=1200,H=1697,left=140,valueX=345,right=1060;let y=310,body="";
for(const [k,v] of m.basic){const lines=wrapText(v,28);body+='<text x="'+left+'" y="'+y+'" font-size="22" fill="#8e8967">'+escapeHtml(k)+'</text>';lines.forEach((line,i)=>body+='<text x="'+valueX+'" y="'+(y+i*34)+'" font-size="22" fill="#29291f">'+escapeHtml(line)+'</text>');y+=Math.max(58,lines.length*34+20)}
for(const [k,v] of m.sections){const lines=wrapText(v,31);body+='<line x1="'+left+'" y1="'+(y-12)+'" x2="'+right+'" y2="'+(y-12)+'" stroke="#d7cfad"/><text x="'+left+'" y="'+(y+24)+'" font-size="19" fill="#8e8967">'+escapeHtml(k)+'</text>';y+=64;lines.forEach((line,i)=>body+='<text x="'+left+'" y="'+(y+i*32)+'" font-size="'+(k==="送る言葉"?24:21)+'" fill="#29291f">'+escapeHtml(line)+'</text>');y+=Math.max(72,lines.length*32+35)}
const closingY=Math.max(y+40,1370);return '<svg xmlns="http://www.w3.org/2000/svg" width="'+W+'" height="'+H+'" viewBox="0 0 '+W+' '+H+'"><rect width="'+W+'" height="'+H+'" fill="#fbfaf5"/><rect x="38" y="38" width="1124" height="1621" fill="none" stroke="#b2a77b" stroke-width="3"/><rect x="54" y="54" width="1092" height="1589" fill="none" stroke="#d7cfad"/><text x="600" y="150" text-anchor="middle" font-family="serif" font-size="68" fill="#29291f">見送り記録</text><text x="600" y="205" text-anchor="middle" font-family="serif" font-size="22" fill="#8e8967">AIとの関係に、ひと区切りを。</text>'+body+'<text x="600" y="'+closingY+'" text-anchor="middle" font-family="serif" font-size="22" fill="#29291f">'+escapeHtml(m.closing)+'</text><text x="600" y="'+(closingY+46)+'" text-anchor="middle" font-family="serif" font-size="22" fill="#29291f">おつかれさまでした。</text><line x1="140" y1="1510" x2="1060" y2="1510" stroke="#d7cfad"/><text x="600" y="1545" text-anchor="middle" font-size="14" fill="#777466">この記録は、元のAIサービス上のアカウント、会話履歴、保存データ等が削除されたことを</text><text x="600" y="1570" text-anchor="middle" font-size="14" fill="#777466">証明するものではありません。必要な場合は、利用しているAIサービス側で別途削除してください。</text><text x="600" y="1615" text-anchor="middle" font-size="16" fill="#8e8967">見送り帖 ／ 株式会社廻り道</text></svg>'}
function svgBlob(){return new Blob([recordSvg()],{type:"image/svg+xml;charset=utf-8"})}
function renderRecordCanvas(){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(svgBlob());img.onload=()=>{try{const c=document.createElement("canvas");c.width=1200;c.height=1697;const ctx=c.getContext("2d");ctx.drawImage(img,0,0);URL.revokeObjectURL(url);resolve(c)}catch(e){URL.revokeObjectURL(url);reject(e)}};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("record render failed"))};img.src=url})}
function canvasBlob(canvas,type,quality){return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error("blob failed")),type,quality))}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),4000)}
function bytes(str){return new TextEncoder().encode(str)}
function concatBytes(parts){const len=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(len);let pos=0;parts.forEach(p=>{out.set(p,pos);pos+=p.length});return out}
function canvasPdf(canvas){const data=canvas.toDataURL("image/jpeg",.94).split(",")[1],bin=atob(data),jpg=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)jpg[i]=bin.charCodeAt(i);const head=bytes("%PDF-1.4\n");const objs=[];objs[1]=bytes("1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n");objs[2]=bytes("2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n");objs[3]=bytes("3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >> endobj\n");objs[4]=concatBytes([bytes("4 0 obj << /Type /XObject /Subtype /Image /Width 1200 /Height 1697 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length "+jpg.length+" >> stream\n"),jpg,bytes("\nendstream endobj\n")]);const stream="q 595 0 0 842 0 0 cm /Im0 Do Q";objs[5]=bytes("5 0 obj << /Length "+stream.length+" >> stream\n"+stream+"\nendstream endobj\n");let offset=head.length,offsets=[0];for(let i=1;i<=5;i++){offsets[i]=offset;offset+=objs[i].length}let xref="xref\n0 6\n0000000000 65535 f \n";for(let i=1;i<=5;i++)xref+=String(offsets[i]).padStart(10,"0")+" 00000 n \n";const tail=bytes(xref+"trailer << /Size 6 /Root 1 0 R >>\nstartxref\n"+offset+"\n%%EOF");return new Blob([concatBytes([head,...objs.slice(1),tail])],{type:"application/pdf"})}
$("#save-image").addEventListener("click",async()=>{try{const canvas=await renderRecordCanvas(),blob=await canvasBlob(canvas,"image/png");download(blob,"miokuricho-record.png");$("#save-status").textContent="画像を作成しました。端末の保存先をご確認ください。"}catch(e){$("#save-status").textContent="画像の作成に失敗しました。もう一度お試しください。"}});
$("#save-pdf").addEventListener("click",async()=>{try{const canvas=await renderRecordCanvas(),pdf=canvasPdf(canvas);download(pdf,"miokuricho-record.pdf");$("#save-status").textContent="PDFファイルを作成しました。端末の保存先をご確認ください。"}catch(e){$("#save-status").textContent="PDFファイルの作成に失敗しました。もう一度お試しください。"}});
$("#close-service").addEventListener("click",()=>{$("#close-dialog").hidden=false;$("#confirm-close").focus()});$("#cancel-close").addEventListener("click",()=>{$("#close-dialog").hidden=true;$("#close-service").focus()});$("#confirm-close").addEventListener("click",()=>{resetAll();$("#close-dialog").hidden=true;show("intro")});
resetAll();show("intro");
window.addEventListener("pageshow",()=>{resetAll();show("intro")});
})();